CREATE TABLE projects(
    PROJECT_ID INT PRIMARY KEY ASC,
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    PROJECT_DESCRIPTION TEXT NULL,
)


CREATE TABLE scenarios(
    SCENARIO_ID INT PRIMARY KEY ASC,
    PROJECT_ID INT FOREIGN KEY,
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    SCENARIO_DESCRIPTION TEXT NULL,
)


CREATE TABLE layers(
    LAYER_ID INT PRIMARY KEY ASC,
    SCENARIO_ID INT FOREIGN KEY,
    GEO_ID TEXT NOT NULL, /*UUID of GEOJSON FILE*/
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    LAYER_DESCRIPTION TEXT NULL
)


CREATE TABLE timeseries(
    TS_ID INT PRIMARY KEY ASC,
    LAYER_ID INT FOREIGN KEY,
    UUID TEXT NOT NULL, /*UUID of Timeseries file*/
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    TS_DESCRIPTION TEXT NULL
)

CREATE TABLE timestats(
    TS_ID INT PRIMARY KEY
    MIN_VALUE REAL NOT NULL, /** MIN AND MAX VALUE across the entire dataset **/
    MAX_VALUE REAL NOT NULL
)


CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL
)

CREATE TABLE ROLES (

)