CREATE TABLE projects(
    PROJECT_ID TEXT PRIMARY KEY,
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    PROJECT_DESCRIPTION TEXT NULL
);


/**/
CREATE TABLE scenarios(
    SCENARIO_ID TEXT PRIMARY KEY,
    PROJECT_ID TEXT,
    ORIGIN_NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NULL,
    SCENARIO_DESCRIPTION TEXT NULL,
    FOREIGN KEY(PROJECT_ID) REFERENCES projects(PROJECT_ID)
);